#### Working on C4.5 Algorithm
#### Target Variable is discrete  (containing classes )
#### Predictor Variable is discrete + Continous

#### https://sefiks.com/2018/05/13/a-step-by-step-c4-5-decision-tree-example/

In [1]:
import pandas as pd
import numpy as np

In [2]:
d = {'Outlook': ['Sunny', 'Sunny','Overcast','Rain','Rain','Rain','Overcast','Sunny','Sunny','Rain','Sunny','Overcast','Overcast','Rain']
, 'Temp': [85,80,83,70,68,65,64,72,69,75,75,72,81,71],
'Humidity':[85,90,78,96,80,70,65,95,70,80,70,90,75,80],
'Wind':['Weak','Strong','Weak','Weak','Weak','Strong','Strong','Weak','Weak','Weak','Strong','Strong','Weak','Strong'],
'Decision':['No','No','Yes','Yes','Yes','No','Yes','No','Yes','Yes','Yes','Yes','Yes','No']}
df = pd.DataFrame(data=d)

In [3]:
df

     Outlook  Temp  Humidity    Wind Decision
0      Sunny    85        85    Weak       No
1      Sunny    80        90  Strong       No
2   Overcast    83        78    Weak      Yes
3       Rain    70        96    Weak      Yes
4       Rain    68        80    Weak      Yes
5       Rain    65        70  Strong       No
6   Overcast    64        65  Strong      Yes
7      Sunny    72        95    Weak       No
8      Sunny    69        70    Weak      Yes
9       Rain    75        80    Weak      Yes
10     Sunny    75        70  Strong      Yes
11  Overcast    72        90  Strong      Yes
12  Overcast    81        75    Weak      Yes
13      Rain    71        80  Strong       No

In [4]:
for row in df:
    print(df[row].dtype)

object
int64
int64
object
object

In [5]:
### Define the Entropy
def entropy(Target):
    Count=0
    for i in df.groupby(Target).size():
        Total=np.sum(df.groupby(Target).size())
        entropy=-((i/Total)*np.log2((i/Total)))
        Count=Count+entropy
    return Count
entropy(Target=df['Decision'])

0.9402859586706311

In [6]:
def Root_Node(Predictor,Target):
    for row in Predictor:
        print(row)
Root_Node(Predictor=df[['Wind','Outlook']],Target=df['Decision'])

Wind
Outlook

In [7]:
def Root_Node(Predictor,Target):
    
    
    for row in Predictor:
        '''
        For Categorical Data
        '''
        print(row)
        Count=0
       
        if Predictor[row].dtype=='object':
            df_merge=pd.concat([Predictor[row],Target],axis=1)
            grouping=df_merge.groupby(row)
            Total=df_merge.count()[1]
            
            for ix in (df_merge[row].unique()):
               # Count=0
                unique=grouping.get_group(ix).iloc[:,1].value_counts()
                Total_group=grouping.get_group(ix).count()[1]
                ratio=(Total_group/Total)
                #print(Total_group)
                for jx in unique:
                    #print(jx)
                    ''''''
                    Entropy=-(Total_group/Total)*((jx/Total_group)*np.log2((jx/Total_group)))
                    Count=Count+Entropy
                Gain=entropy(Target=df['Decision'])-Count
            print(Gain)
            #return(Count)
        if Predictor[row].dtype=='int64':
            '''
            For Continous Variable
            In this we are using Threshold Values to predict the Binary Split.
            
            '''
            
            df_merger_continous=pd.concat([Predictor[row],Target],axis=1)
            df_merger_continous=df_merger_continous.sort_values(by=row,ascending=True)
            distinct_value=df_merger_continous[row].unique()
            Count_all=0
            Gain_cont=0
            for m,n in enumerate(distinct_value):
                if True:
                    df_less_equal=df_merger_continous.loc[df_merger_continous[row] <= n]
                    Total1=np.sum(df_less_equal.iloc[:,1].value_counts())
                    Count1=0
                    for ix in df_less_equal.iloc[:,1].value_counts():
                        Entropy1=-(ix/Total1)*(np.log2(ix/Total1))
                        Count1=Count1+Entropy1
                if True:
                    df_greater=df_merger_continous.loc[df_merger_continous[row] > n]
                    Total2=np.sum(df_greater.iloc[:,1].value_counts())
                    Count2=0
                    for iz in df_greater.iloc[:,1].value_counts():
                        Entropy2=-(iz/Total2)*(np.log2(iz/Total2))
                        Count2=Count2+Entropy2
                Count_all=Count1+Count2
                Gain_cont=entropy(Target=df['Decision'])-(Count_all)
                print(Gain_cont)

            
#Root_Node(Predictor=df[['Outlook','Wind']],Target=df['Decision'])
Root_Node(Predictor=df[['Wind','Outlook','Humidity','Temp']],Target=df['Decision'])

Wind
0.04812703040826949
Outlook
0.24674981977443922
Humidity
-0.020950646052244726
-0.8419427602431702
-0.7727181960549534
-0.709736462977723
-0.7948691422926577
-0.9410049405600616
-0.9780098753838584
-0.020950646052244726
0.0
Temp
-0.020950646052244726
-0.9780098753838584
-0.9236701799844984
-0.8419427602431702
-0.7727181960549534
-0.9324438783088236
-0.9324438783088236
-0.9410049405600616
-0.9236701799844984
-0.9780098753838584
0.049794318451139796
0.0

#### ID3 Algorithms

#### All Variables including Target and Independent are Categorical

In [8]:
d = {'Outlook': ['sunny','sunny','overcast','rainy','rainy','rainy','overcast','sunny','sunny','rainy','sunny','overcast','overcast','rainy'], 
     'Temp': ['Hot','Hot','Hot','Mild','Cool','Cool','Cool','Mild','Cool','Mild','Mild','Mild','Hot','Mild'], 
     'Humidity':['High','High','High','High','Normal','Normal','Normal','High','Normal','Normal','Normal','High','Normal','High']
     ,'Windy':['False','True','False','False','False','True','True','False','False','False','True','True','False','True'],
     'PlayGolf':['No','No','Yes','Yes','Yes','No','Yes','No','Yes','Yes','Yes','Yes','Yes','No']}
df = pd.DataFrame(data=d)
df

     Outlook  Temp Humidity  Windy PlayGolf
0      sunny   Hot     High  False       No
1      sunny   Hot     High   True       No
2   overcast   Hot     High  False      Yes
3      rainy  Mild     High  False      Yes
4      rainy  Cool   Normal  False      Yes
5      rainy  Cool   Normal   True       No
6   overcast  Cool   Normal   True      Yes
7      sunny  Mild     High  False       No
8      sunny  Cool   Normal  False      Yes
9      rainy  Mild   Normal  False      Yes
10     sunny  Mild   Normal   True      Yes
11  overcast  Mild     High   True      Yes
12  overcast   Hot   Normal  False      Yes
13     rainy  Mild     High   True       No

In [9]:
## Changing DataFrae to Matrix
dfmat = df.values
dfmat

array([['sunny', 'Hot', 'High', 'False', 'No'],
       ['sunny', 'Hot', 'High', 'True', 'No'],
       ['overcast', 'Hot', 'High', 'False', 'Yes'],
       ['rainy', 'Mild', 'High', 'False', 'Yes'],
       ['rainy', 'Cool', 'Normal', 'False', 'Yes'],
       ['rainy', 'Cool', 'Normal', 'True', 'No'],
       ['overcast', 'Cool', 'Normal', 'True', 'Yes'],
       ['sunny', 'Mild', 'High', 'False', 'No'],
       ['sunny', 'Cool', 'Normal', 'False', 'Yes'],
       ['rainy', 'Mild', 'Normal', 'False', 'Yes'],
       ['sunny', 'Mild', 'Normal', 'True', 'Yes'],
       ['overcast', 'Mild', 'High', 'True', 'Yes'],
       ['overcast', 'Hot', 'Normal', 'False', 'Yes'],
       ['rainy', 'Mild', 'High', 'True', 'No']], dtype=object)

In [10]:
## Calculate the Enropy of Data-set
target=dfmat[:,-1]
def Entropy(target,m):
    unique_target, counts_target = np.unique(target, return_counts=True)
    counts_target=counts_target/m
    return -np.sum((counts_target*np.log2(counts_target)))

In [11]:
def attributes(dfmat):
    for j in range(dfmat[:,0:4].shape[1]):
        C=0
        ix=dfmat[:,[j,-1]]
        ut, ct = np.unique(ix[:,0], return_counts=True)
        for i in range(len(ut)):
            m=len(ix[np.where(ix==ut[i])[0],:])
            target=ix[np.where(ix==ut[i])[0],:]
            Count=m/len(dfmat)*Entropy(target,m)
            C=Count+C      
    return C
attributes(dfmat)

0.8921589282623617

In [12]:
def find_winner(dfmat):
    IG = []
    for key in df.keys()[:-1]:
        IG.append(Entropy(dfmat[:,-1],14)-attributes(dfmat))
    return df.keys()[:-1][np.argmax(IG)]
df.keys()[:-1]

Index(['Outlook', 'Temp', 'Humidity', 'Windy'], dtype='object')

In [13]:
node=find_winner(dfmat)
node

'Outlook'

#### CART Algorithm

In [14]:
d = {'tutorials': ['all','some','all','all','some','all','some','some','some','all','some','all','some','some','some'], 
     'labs': ['complete','partial','complete','complete','partial','complete','complete','partial','complete','complete','partial','complete','partial','partial','partial'], 
     'exam':[74,23,61,74,25,61,54,42,55,75,13,73,31,12,11]}
df = pd.DataFrame(data=d)
df

   tutorials      labs  exam
0        all  complete    74
1       some   partial    23
2        all  complete    61
3        all  complete    74
4       some   partial    25
5        all  complete    61
6       some  complete    54
7       some   partial    42
8       some  complete    55
9        all  complete    75
10      some   partial    13
11       all  complete    73
12      some   partial    31
13      some   partial    12
14      some   partial    11

In [15]:
print('Standard Deviation of Target is',df.exam.std())


def VarReduction(df):
    
    
    if df[df.columns[len(df.columns)-1]].dtypes=='int64':
        print('Variance Redcuction by Variables')
        for row in df.iloc[:, :-1]:
            Total=len(df)
            Count=0
            for i in range(len(df[row].unique())):
                std=((df[row].value_counts()[i]/Total)*(df.groupby(row).std().loc[::-1].values[i]))
                Count=Count+std
                Var_reduce=df.exam.std()-Count
            print(row,'-->',Var_reduce)
    else:
        print('Your Target Variable is not float or integer')
VarReduction(df=df)

Standard Deviation of Target is 24.51180473626068
Variance Redcuction by Variables
tutorials --> [11.43919394]
labs --> [14.16367342]